Changes & Updates in the Grammar in the Workshop Modules (Work on Progress)
shresthagrawal/learnp2p pull request #5
Opened 2020-04-14 12:30 UTC by Xavian-Brooker

Corrected the Grammar of the introduction page, and of the module pages. Also trying to complete the TODO. Work is in progress.

2020-04-14 19:37 UTC, shresthagrawal requested changes

2020-04-14 19:37 UTC, shresthagrawal commented on index.html
> +  <link rel="manifest" href="./media/favicons/site.webmanifest"> -->
can you reset the changes made in the design files @Xavian-Brooker

2020-04-14 19:37 UTC, shresthagrawal commented on resource/themes/dark.css
> +<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-defaults.css">
same as above!

2020-04-15 07:06 UTC, Xavian-Brooker commented on resource/themes/dark.css
> +<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-defaults.css">
What changes do you want me to reset?

2020-04-22 11:30 UTC, shresthagrawal approved these changes

2020-04-22 11:30 UTC, merged